### ISSUE TITLE
bunker_base cant find ugv_sdk package when using catkin build. 

### ISSUE THREAD

**Issue by fakhruzakuantii** [agilexrobotics/bunker_ros#2]
Hi, 

I am building my ros workspace using catkin tools (catkin build) instead of using catkin_make. 
However it does not work and return this error. 

`CMake Error at /home/user1/bunker_ws/devel/share/ugv_sdk/cmake/ugv_sdkConfig.cmake:173 (message):
  Project 'bunker_base' tried to find library 'ugv_sdk'.  The library is
  neither a target nor built/installed properly.  Did you compile project
  'ugv_sdk'? Did you find_package() it before the subdirectory containing its
  code is included?
`

Please assist. 
Thank you

**Comment by dashun1234** [comment]
You will need to setup the ugv_sdk  first if you would like to creat your own ros workspace and build it on your laptop or own controller. The ugv_sdk is mainly for the communication between ros and the chassis. Here is the link for the ugv_sdk. And it has the detailed instruction for the use of it. @fakhruzakuantii 
https://github.com/agilexrobotics/ugv_sdk

**Comment by fakhruzakuantii** [comment]
This pull (https://github.com/agilexrobotics/ugv_sdk/pull/3) fixed my issue.
Thank you.
